name: model-supervisé RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.Exam_A57 }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python seif.py
          # Write your CML report
          echo "## Metriques:" >> report.md
